### ISSUE TITLE
I think the order of parts of the installation instructions is wrong

### ISSUE THREAD

**Issue by fds-github** [MattRogowski/Automatic-Subscriptions#1]
Here http://mods.mybb.com/view/automatic-subscriptions it says to add "{$automaticsubscriptions}" to two templates, then activate the plug-in.  The first part of the activate code calls deactivate, which removes those strings.  I think they have to be added in afterwards.

**Comment by josharcheruk** [comment]
I can replicate this, and it's annoying!
