### ISSUE TITLE
Instant notifications not working

### ISSUE THREAD

**Issue by fds-github** [MattRogowski/Automatic-Subscriptions#2]
I believe the wrong value is being passed as the second parameter to add_subscribed_thread.  I changed the code at Line 273 of automaticsubscriptions.php to the below and it works for me now.

```
    $notification = ($user['subscriptionmethod'] == 2) ? 1 : 0;
    add_subscribed_thread($tid, $notification, $user['uid']);
```

**Comment by josharcheruk** [comment]
I see line 273 as:

`function automaticsubscriptions_admin_formcontainer_output_row($pluginargs)`

You changed the entire line to what you posted above?

**Comment by dfaure-kdab** [comment]
No, he means where the call to add_subscribed_thread is. The int values don't match.

See the more complete merge request I just created, https://github.com/MattRogowski/Automatic-Subscriptions/pull/5

**Comment by MattRogowski** [comment]
Annoying, I know I spent ages struggling with this plugin to get things to work as expected and confusing myself about which values to use, obviously I missed this.

**Comment by dfaure-kdab** [comment]
Thanks. Might I suggest a comment near that fix? To the casual reader (or for you in a year) the reason for this decrement is going to be really not obvious.

Can you let me know in which version of the plugin the fix will be, so I can find out if I need to patch it next time I install it?

**Comment by MattRogowski** [comment]
Comment added - am about to release v1.2.2

Thanks again for the fix and sorry for the long delay in applying it
