### ISSUE TITLE
Error generated

### ISSUE THREAD

**Issue by rroberg** [MattRogowski/Automatic-Subscriptions#4]
I have a site that provides users access to several "groups", each of which has their own private forum.  After installing the plugin, when trying to change groups, the following error occurs.
https://cloud.githubusercontent.com/assets/17398002/13208889/d4706e20-d8da-11e5-9626-a5ccc2732453.png

Any help would be greatly appreciated

**Comment by MattRogowski** [comment]
I know this has been open for almost a year but it's not an error generated by MyBB let alone the plugin, no idea how anything in that screenshot relates to a MyBB forum or this plugin.
